"""add_ai_connectors

Revision ID: 32a0f5a761c5
Revises: None
Create Date: 2026-06-17 12:33:38.036543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32a0f5a761c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('openai_api_key', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('cerebras_api_key', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('preferred_ai_provider', sa.String(length=50), nullable=True, server_default='default'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_ai_provider')
    op.drop_column('users', 'cerebras_api_key')
    op.drop_column('users', 'openai_api_key')
    # ### end Alembic commands ###
